POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
PIMORONI_TRACKBALL_ADDRESS = 0x0A
PIMORONI_TRACKBALL_SCALE = 3
PIMORONI_TRACKBALL_DEBOUNCE_CYCLES = 3
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
