name: Build QMK firmware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          export QMK_HOME='~/qmk_firmware'
          pip install milc
          python3 -m pip install --user qmk
          qmk setup -y
          ls ~/qmk_firmware
          cp -r ~/work/qmk-config/qmk-config/keyboards ~/qmk_firmware/

      - name: Set Release Date
        run: echo "RELEASE_DATE=$(date --rfc-3339=seconds)" >> ${GITHUB_ENV}

      - name: Build
        run: |
          qmk compile -kb crkkbd -km dmjgilbert

      - name: Copy built firmware
        run: |
          rm -f $GITHUB_WORKSPACE/*.hex
          rm -f $GITHUB_WORKSPACE/*.bin
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec \cp '{}' $GITHUB_WORKSPACE \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec \cp '{}' $GITHUB_WORKSPACE \;
          ls $GITHUB_WORKSPACE

      - name: Package assets
        run: |
          mkdir ~/qmk_firmware/firmware
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec mv '{}' ~/qmk_firmware/firmware \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec mv '{}' ~/qmk_firmware/firmware \;
          tar -cvf /home/runner/filename.tar /home/runner/qmk_firmware
          mv /home/runner/filename.tar /home/runner/qmk_firmware/firmware/filename.tar

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{env.RELEASE_DATE}}"
          title: ${{ env.ReleaseVersion }}
          prerelease: true
          files: |
            /home/runner/qmk_firmware/firmware/*
