name: Build QMK firmware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/qmk_firmware
          key: ${{ runner.os }}-qmk_firmware

      - name: Setup
        run: |
          export QMK_HOME='~/qmk_firmware'
          pip install milc
          python3 -m pip install --user qmk
          qmk setup -y
          ls ~/qmk_firmware
          cp -r ~/work/qmk-firmware/qmk_firmware/keyboards ~/qmk_firmware/

      - name: Set Release Date
        run: echo "RELEASE_DATE=$(date --rfc-3339=seconds)" >> ${GITHUB_ENV}

      - name: Build
        run: |
          qmk compile -kb crkkbd -km dmjgilbert

      - name: Copy built firmware
        run: |
          rm -f $GITHUB_WORKSPACE/*.hex
          rm -f $GITHUB_WORKSPACE/*.bin
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec \cp '{}' $GITHUB_WORKSPACE \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec \cp '{}' $GITHUB_WORKSPACE \;
          ls $GITHUB_WORKSPACE

      - name: Package assets
        run: |
          mkdir ~/qmk_firmware/firmware
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec mv '{}' ~/qmk_firmware/firmware \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec mv '{}' ~/qmk_firmware/firmware \;
          tar -cvf /home/runner/filename.tar /home/runner/qmk_firmware
          mv /home/runner/filename.tar /home/runner/qmk_firmware/firmware/filename.tar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /home/runner/qmk_firmware/firmware/*
